In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('pokemon_alopez247.csv')

In [3]:
df.head(5)

Number        Name Type_1  Type_2  Total  HP  Attack  Defense  Sp_Atk  \
0       1   Bulbasaur  Grass  Poison    318  45      49       49      65   
1       2     Ivysaur  Grass  Poison    405  60      62       63      80   
2       3    Venusaur  Grass  Poison    525  80      82       83     100   
3       4  Charmander   Fire     NaN    309  39      52       43      60   
4       5  Charmeleon   Fire     NaN    405  58      64       58      80   

   Sp_Def  ...  Color  hasGender  Pr_Male Egg_Group_1  Egg_Group_2  \
0      65  ...  Green       True    0.875     Monster        Grass   
1      80  ...  Green       True    0.875     Monster        Grass   
2     100  ...  Green       True    0.875     Monster        Grass   
3      50  ...    Red       True    0.875     Monster       Dragon   
4      65  ...    Red       True    0.875     Monster       Dragon   

   hasMegaEvolution Height_m Weight_kg  Catch_Rate      Body_Style  
0             False     0.71       6.9          45       quadruped  
1             False     0.99      13.0          45       quadruped  
2              True     2.01     100.0          45       quadruped  
3             False     0.61       8.5          45  bipedal_tailed  
4             False     1.09      19.0          45  bipedal_tailed  

[5 rows x 23 columns]

In [4]:
df.columns

Index(['Number', 'Name', 'Type_1', 'Type_2', 'Total', 'HP', 'Attack',
       'Defense', 'Sp_Atk', 'Sp_Def', 'Speed', 'Generation', 'isLegendary',
       'Color', 'hasGender', 'Pr_Male', 'Egg_Group_1', 'Egg_Group_2',
       'hasMegaEvolution', 'Height_m', 'Weight_kg', 'Catch_Rate',
       'Body_Style'],
      dtype='object')

In [5]:
df = df[['isLegendary','Generation', 'Type_1', 'Type_2', 'HP', 'Attack', 'Defense', 'Sp_Atk', 'Sp_Def', 'Speed','Color','Egg_Group_1','Height_m','Weight_kg','Body_Style']]

In [6]:
df

isLegendary  Generation   Type_1  Type_2   HP  Attack  Defense  Sp_Atk  \
0          False           1    Grass  Poison   45      49       49      65   
1          False           1    Grass  Poison   60      62       63      80   
2          False           1    Grass  Poison   80      82       83     100   
3          False           1     Fire     NaN   39      52       43      60   
4          False           1     Fire     NaN   58      64       58      80   
..           ...         ...      ...     ...  ...     ...      ...     ...   
716         True           6     Dark  Flying  126     131       95     131   
717         True           6   Dragon  Ground  108     100      121      81   
718         True           6     Rock   Fairy   50     100      150     100   
719         True           6  Psychic   Ghost   80     110       60     150   
720         True           6     Fire   Water   80     110      120     130   

     Sp_Def  Speed   Color   Egg_Group_1  Height_m  Weight_kg       Body_Style  
0        65     45   Green       Monster      0.71        6.9        quadruped  
1        80     60   Green       Monster      0.99       13.0        quadruped  
2       100     80   Green       Monster      2.01      100.0        quadruped  
3        50     65     Red       Monster      0.61        8.5   bipedal_tailed  
4        65     80     Red       Monster      1.09       19.0   bipedal_tailed  
..      ...    ...     ...           ...       ...        ...              ...  
716      98     99     Red  Undiscovered      5.79      203.0        two_wings  
717      95     95   Green  Undiscovered      5.00      305.0  serpentine_body  
718     150     50    Pink  Undiscovered      0.71        8.8        head_arms  
719     130     70  Purple  Undiscovered      0.51        9.0        head_only  
720      90     70   Brown  Undiscovered      1.70      195.0        quadruped  

[721 rows x 15 columns]

In [7]:
#Turning bool values of isLegendary in 0's & 1's
df['isLegendary'] = df['isLegendary'].astype(int)

In [8]:
df

isLegendary  Generation   Type_1  Type_2   HP  Attack  Defense  Sp_Atk  \
0              0           1    Grass  Poison   45      49       49      65   
1              0           1    Grass  Poison   60      62       63      80   
2              0           1    Grass  Poison   80      82       83     100   
3              0           1     Fire     NaN   39      52       43      60   
4              0           1     Fire     NaN   58      64       58      80   
..           ...         ...      ...     ...  ...     ...      ...     ...   
716            1           6     Dark  Flying  126     131       95     131   
717            1           6   Dragon  Ground  108     100      121      81   
718            1           6     Rock   Fairy   50     100      150     100   
719            1           6  Psychic   Ghost   80     110       60     150   
720            1           6     Fire   Water   80     110      120     130   

     Sp_Def  Speed   Color   Egg_Group_1  Height_m  Weight_kg       Body_Style  
0        65     45   Green       Monster      0.71        6.9        quadruped  
1        80     60   Green       Monster      0.99       13.0        quadruped  
2       100     80   Green       Monster      2.01      100.0        quadruped  
3        50     65     Red       Monster      0.61        8.5   bipedal_tailed  
4        65     80     Red       Monster      1.09       19.0   bipedal_tailed  
..      ...    ...     ...           ...       ...        ...              ...  
716      98     99     Red  Undiscovered      5.79      203.0        two_wings  
717      95     95   Green  Undiscovered      5.00      305.0  serpentine_body  
718     150     50    Pink  Undiscovered      0.71        8.8        head_arms  
719     130     70  Purple  Undiscovered      0.51        9.0        head_only  
720      90     70   Brown  Undiscovered      1.70      195.0        quadruped  

[721 rows x 15 columns]

In [10]:
df['Type_1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [11]:
def dummy_creation(df, dummy_categories):
    for i in dummy_categories:
        df_dummy = pd.get_dummies(df[i])
        df = pd.concat([df,df_dummy],axis=1)
        df = df.drop(i, axis=1)
    return(df)

In [12]:
df = dummy_creation(df, ['Egg_Group_1', 'Body_Style', 'Color','Type_1', 'Type_2'])

In [13]:
df.head(5)

isLegendary  Generation  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  \
0            0           1  45      49       49      65      65     45   
1            0           1  60      62       63      80      80     60   
2            0           1  80      82       83     100     100     80   
3            0           1  39      52       43      60      50     65   
4            0           1  58      64       58      80      65     80   

   Height_m  Weight_kg  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
0      0.71        6.9  ...      0      0       0    0       0       1   
1      0.99       13.0  ...      0      0       0    0       0       1   
2      2.01      100.0  ...      0      0       0    0       0       1   
3      0.61        8.5  ...      0      0       0    0       0       0   
4      1.09       19.0  ...      0      0       0    0       0       0   

   Psychic  Rock  Steel  Water  
0        0     0      0      0  
1        0     0      0      0  
2        0     0      0      0  
3        0     0      0      0  
4        0     0      0      0  

[5 rows x 85 columns]

In [16]:
def train_test_splitter(DataFrame,column):
    df_train = DataFrame.loc[df[column] != 1]
    df_test = DataFrame.loc[df[column] == 1]
    
    df_train = df_train.drop(column, axis = 1)
    df_test = df_test.drop(column, axis = 1)
    
    return(df_train, df_test)
    
df_train, df_test = train_test_splitter(df, 'Generation')

In [17]:
df_train.head(5)

isLegendary  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Height_m  \
151            0  45      49       65      49      65     45      0.89   
152            0  60      62       80      63      80     60      1.19   
153            0  80      82      100      83     100     80      1.80   
154            0  39      52       43      60      50     65      0.51   
155            0  58      64       58      80      65     80      0.89   

     Weight_kg  Amorphous  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
151        6.4          0  ...      0      0       0    0       0       0   
152       15.8          0  ...      0      0       0    0       0       0   
153      100.5          0  ...      0      0       0    0       0       0   
154        7.9          0  ...      0      0       0    0       0       0   
155       19.0          0  ...      0      0       0    0       0       0   

     Psychic  Rock  Steel  Water  
151        0     0      0      0  
152        0     0      0      0  
153        0     0      0      0  
154        0     0      0      0  
155        0     0      0      0  

[5 rows x 84 columns]

In [18]:
df_test.head(5)

isLegendary  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Height_m  \
0            0  45      49       49      65      65     45      0.71   
1            0  60      62       63      80      80     60      0.99   
2            0  80      82       83     100     100     80      2.01   
3            0  39      52       43      60      50     65      0.61   
4            0  58      64       58      80      65     80      1.09   

   Weight_kg  Amorphous  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
0        6.9          0  ...      0      0       0    0       0       1   
1       13.0          0  ...      0      0       0    0       0       1   
2      100.0          0  ...      0      0       0    0       0       1   
3        8.5          0  ...      0      0       0    0       0       0   
4       19.0          0  ...      0      0       0    0       0       0   

   Psychic  Rock  Steel  Water  
0        0     0      0      0  
1        0     0      0      0  
2        0     0      0      0  
3        0     0      0      0  
4        0     0      0      0  

[5 rows x 84 columns]

In [19]:
def label_delineator(df_train, df_test, label):
    
    train_data = df_train.drop(label, axis=1).values
    train_labels = df_train[label].values
    test_data = df_test.drop(label,axis=1).values
    test_labels = df_test[label].values
    return(train_data, train_labels, test_data, test_labels)

In [20]:
train_data,train_labels,test_data,test_labels = label_delineator(df_train, df_test, 'isLegendary')

In [21]:
train_data

array([[ 45.,  49.,  65., ...,   0.,   0.,   0.],
       [ 60.,  62.,  80., ...,   0.,   0.,   0.],
       [ 80.,  82., 100., ...,   0.,   0.,   0.],
       ...,
       [ 50., 100., 150., ...,   0.,   0.,   0.],
       [ 80., 110.,  60., ...,   0.,   0.,   0.],
       [ 80., 110., 120., ...,   0.,   0.,   1.]])

In [22]:
train_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
test_data

array([[ 45.,  49.,  49., ...,   0.,   0.,   0.],
       [ 60.,  62.,  63., ...,   0.,   0.,   0.],
       [ 80.,  82.,  83., ...,   0.,   0.,   0.],
       ...,
       [ 91., 134.,  95., ...,   0.,   0.,   0.],
       [106., 110.,  90., ...,   0.,   0.,   0.],
       [100., 100., 100., ...,   0.,   0.,   0.]])

In [24]:
from sklearn import preprocessing
def data_normalizer(train_data, test_data):
    train_data = preprocessing.MinMaxScaler().fit_transform(train_data)
    test_data = preprocessing.MinMaxScaler().fit_transform(test_data)
    return(train_data, test_data)
train_data, test_data = data_normalizer(train_data, test_data)

In [25]:
train_data

array([[0.17322835, 0.275     , 0.26666667, ..., 0.        , 0.        ,
        0.        ],
       [0.23228346, 0.35625   , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.31102362, 0.48125   , 0.42222222, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.19291339, 0.59375   , 0.64444444, ..., 0.        , 0.        ,
        0.        ],
       [0.31102362, 0.65625   , 0.24444444, ..., 0.        , 0.        ,
        0.        ],
       [0.31102362, 0.65625   , 0.51111111, ..., 0.        , 0.        ,
        1.        ]])

In [26]:
test_data

array([[0.14583333, 0.34108527, 0.25142857, ..., 0.        , 0.        ,
        0.        ],
       [0.20833333, 0.44186047, 0.33142857, ..., 0.        , 0.        ,
        0.        ],
       [0.29166667, 0.59689922, 0.44571429, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.3375    , 1.        , 0.51428571, ..., 0.        , 0.        ,
        0.        ],
       [0.4       , 0.81395349, 0.48571429, ..., 0.        , 0.        ,
        0.        ],
       [0.375     , 0.73643411, 0.54285714, ..., 0.        , 0.        ,
        0.        ]])

In [27]:
length = train_data.shape[1]

model = keras.Sequential()
model.add(keras.layers.Dense(500, activation='relu', input_shape=[length,]))
model.add(keras.layers.Dense(2, activation='softmax'))

In [29]:
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [31]:
model.fit(train_data,train_labels,epochs = 400)

Train on 570 samples
Epoch 1/400
570/570 [==============================] - 0s 143us/sample - loss: 0.2173 - accuracy: 0.9263
Epoch 2/400
570/570 [==============================] - 0s 121us/sample - loss: 0.2137 - accuracy: 0.9263
Epoch 3/400
570/570 [==============================] - 0s 140us/sample - loss: 0.2103 - accuracy: 0.9263
Epoch 4/400
570/570 [==============================] - 0s 132us/sample - loss: 0.2069 - accuracy: 0.9263
Epoch 5/400
570/570 [==============================] - 0s 126us/sample - loss: 0.2034 - accuracy: 0.9263
Epoch 6/400
570/570 [==============================] - 0s 126us/sample - loss: 0.2000 - accuracy: 0.9263
Epoch 7/400
570/570 [==============================] - 0s 149us/sample - loss: 0.1967 - accuracy: 0.9263
Epoch 8/400
570/570 [==============================] - 0s 126us/sample - loss: 0.1934 - accuracy: 0.9263
Epoch 9/400
570/570 [==============================] - 0s 154us/sample - loss: 0.1902 - accuracy: 0.9263
Epoch 10/400
570/570 [============

570/570 [==============================] - 0s 132us/sample - loss: 0.0682 - accuracy: 0.9912
Epoch 79/400
570/570 [==============================] - 0s 139us/sample - loss: 0.0675 - accuracy: 0.9912
Epoch 80/400
570/570 [==============================] - 0s 116us/sample - loss: 0.0669 - accuracy: 0.9912
Epoch 81/400
570/570 [==============================] - 0s 125us/sample - loss: 0.0663 - accuracy: 0.9912
Epoch 82/400
570/570 [==============================] - 0s 125us/sample - loss: 0.0657 - accuracy: 0.9912
Epoch 83/400
570/570 [==============================] - 0s 123us/sample - loss: 0.0651 - accuracy: 0.9912
Epoch 84/400
570/570 [==============================] - 0s 118us/sample - loss: 0.0645 - accuracy: 0.9912
Epoch 85/400
570/570 [==============================] - 0s 119us/sample - loss: 0.0639 - accuracy: 0.9912
Epoch 86/400
570/570 [==============================] - 0s 126us/sample - loss: 0.0633 - accuracy: 0.9912
Epoch 87/400
570/570 [==============================] - 0s 

570/570 [==============================] - 0s 106us/sample - loss: 0.0412 - accuracy: 0.9947
Epoch 156/400
570/570 [==============================] - 0s 98us/sample - loss: 0.0410 - accuracy: 0.9947
Epoch 157/400
570/570 [==============================] - 0s 97us/sample - loss: 0.0408 - accuracy: 0.9947
Epoch 158/400
570/570 [==============================] - 0s 99us/sample - loss: 0.0407 - accuracy: 0.9947
Epoch 159/400
570/570 [==============================] - 0s 107us/sample - loss: 0.0405 - accuracy: 0.9947
Epoch 160/400
570/570 [==============================] - 0s 121us/sample - loss: 0.0403 - accuracy: 0.9947
Epoch 161/400
570/570 [==============================] - 0s 111us/sample - loss: 0.0401 - accuracy: 0.9947
Epoch 162/400
570/570 [==============================] - 0s 100us/sample - loss: 0.0399 - accuracy: 0.9947
Epoch 163/400
570/570 [==============================] - 0s 93us/sample - loss: 0.0397 - accuracy: 0.9947
Epoch 164/400
570/570 [==============================] 

570/570 [==============================] - 0s 95us/sample - loss: 0.0303 - accuracy: 0.9965
Epoch 233/400
570/570 [==============================] - 0s 98us/sample - loss: 0.0302 - accuracy: 0.9965
Epoch 234/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0301 - accuracy: 0.9965
Epoch 235/400
570/570 [==============================] - 0s 98us/sample - loss: 0.0300 - accuracy: 0.9965
Epoch 236/400
570/570 [==============================] - 0s 98us/sample - loss: 0.0299 - accuracy: 0.9965
Epoch 237/400
570/570 [==============================] - 0s 98us/sample - loss: 0.0298 - accuracy: 0.9965
Epoch 238/400
570/570 [==============================] - 0s 96us/sample - loss: 0.0297 - accuracy: 0.9965
Epoch 239/400
570/570 [==============================] - 0s 96us/sample - loss: 0.0295 - accuracy: 0.9965
Epoch 240/400
570/570 [==============================] - 0s 98us/sample - loss: 0.0295 - accuracy: 0.9965
Epoch 241/400
570/570 [==============================] - 0s 

570/570 [==============================] - 0s 100us/sample - loss: 0.0238 - accuracy: 0.9982
Epoch 310/400
570/570 [==============================] - 0s 114us/sample - loss: 0.0237 - accuracy: 0.9982
Epoch 311/400
570/570 [==============================] - 0s 107us/sample - loss: 0.0237 - accuracy: 0.9982
Epoch 312/400
570/570 [==============================] - 0s 109us/sample - loss: 0.0236 - accuracy: 0.9982
Epoch 313/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0235 - accuracy: 0.9982
Epoch 314/400
570/570 [==============================] - 0s 100us/sample - loss: 0.0235 - accuracy: 0.9965
Epoch 315/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0234 - accuracy: 0.9982
Epoch 316/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0233 - accuracy: 0.9982
Epoch 317/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0233 - accuracy: 0.9982
Epoch 318/400
570/570 [==============================] 

570/570 [==============================] - 0s 95us/sample - loss: 0.0194 - accuracy: 1.0000
Epoch 387/400
570/570 [==============================] - 0s 96us/sample - loss: 0.0194 - accuracy: 0.9982
Epoch 388/400
570/570 [==============================] - 0s 97us/sample - loss: 0.0193 - accuracy: 1.0000
Epoch 389/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0193 - accuracy: 1.0000
Epoch 390/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0192 - accuracy: 0.9982
Epoch 391/400
570/570 [==============================] - 0s 97us/sample - loss: 0.0192 - accuracy: 1.0000
Epoch 392/400
570/570 [==============================] - 0s 93us/sample - loss: 0.0191 - accuracy: 1.0000
Epoch 393/400
570/570 [==============================] - 0s 95us/sample - loss: 0.0191 - accuracy: 1.0000
Epoch 394/400
570/570 [==============================] - 0s 97us/sample - loss: 0.0191 - accuracy: 1.0000
Epoch 395/400
570/570 [==============================] - 0s 

In [33]:
loss_value, accuracy_value = model.evaluate(test_data, test_labels)
print(f'Our test accuracy was {accuracy_value}')

151/151 [==============================] - 0s 1ms/sample - loss: 0.0363 - accuracy: 0.9801
Our test accuracy was 0.9801324605941772


In [34]:
def predictor(test_data, test_labels, index):
    prediction = model.predict(test_data)
    if np.argmax(prediction[index]) == test_labels[index]:
        print(f'This was correctly predicted to be a \"{test_labels[index]}\"!')
    else:
        print(f'This was incorrectly predicted to be a \"{np.argmax(prediction[index])}\". It was actually a \"{test_labels[index]}\".')
        return(prediction)

In [35]:
predictor(test_data, test_labels, 149)

This was correctly predicted to be a "1"!
